### ISSUE TITLE
Linking `ecto_autoslug_field`

### ISSUE THREAD

**Issue by sobolevn** [h4cc/slugger#17]
Hi, thanks for the awesome package.

Is there any chance to link [`ecto_autoslug_field`](https://github.com/sobolevn/ecto_autoslug_field) from this package's `readme` since `ecto_autoslug_field` is built on top of the `slugger`?

**Comment by h4cc** [comment]
Thank you for this hint, will add a reference in readme.

**Comment by h4cc** [comment]
Done :D

**Comment by sobolevn** [comment]
Thanks!
