### ISSUE TITLE
Custom config settings doesn't work

### ISSUE THREAD

**Issue by sarjanen** [h4cc/slugger#22]
Hi,
New to elixir so maybe i'm doing something wrong but this is what i've tried:
```
# config.exs
config :slugger, separator_char: ?_
config :slugger, replacement_file: "lib/myapp/replacements.exs"
```
Then `mix compile` try my new settings with `iex -S phoenix.server` -> `Slugger.slugify("A b C") # still "A-b-C"`

Also, is `lib/myapp/*` the right dir to place the replacement file in?  (it doesn't pick up my changes)

**Comment by h4cc** [comment]
Have you tried `mix clean` and then `mix compile`? Also a brutal `rm -rf _build` should work.

My local tests did not need any compile step, because of `@external_resource`.

**Comment by davidcole** [comment]
I'm having the same problem. Where does the custom file go? Where is `lib` relative to? Nowhere seems to work, even with clearing out the build and recompiling.

**Comment by h4cc** [comment]
Could you please show how your folder layout looks like?

When the library is installed via mix it should look somehow like this:

```
config/dev.exs <- Put your own config in here.
deps/slugger/lib/replacements.exs <- This is the default file
priv/slugger_replacements.exs <- This is our custom file.
```

Have you tried using `__DIR__` in your config? Then you could make the path relative to `config/`.

**Comment by LostKobrakai** [comment]
I'm wondering how this should be working when using erlang releases. The packaging will result in a different path for the priv dir and using `:code.priv_dir(:myapp)` would not work in the config.exs.

**Comment by h4cc** [comment]
The idea is to have a _relative_ path from `__DIR__` inside your project, what should work independent from absolute location.

**Comment by LostKobrakai** [comment]
Yeah, but a static relative path is also not present by default in an erlang release. Priv files live in `lib/myapp-0.0.1/priv/`, which is neither a fitting relative path in the dev environment of a mix project nor static as it's including the version of the application. In my opinion the most sane way would be to have the config be a relative path within `/priv` and the application name while using `Path.join(:code.priv_dir(:myapp), rel_path)` within slugger to build an absolute path from both.

**Comment by h4cc** [comment]
Okay, have you tried this? Is there a error message?

Because the replacemenets.exs file is only used at compile. If a different file is used by configuration, it does not need to be inside the release because it has become code at compiletime.

This is the place: https://github.com/h4cc/slugger/blob/master/lib/slugger.ex#L84
