### ISSUE TITLE
Fix deprecation warnings

### ISSUE THREAD

**Issue by kirahowe** [h4cc/slugger#28]
There are some deprecation warnings coming from `lib/slugger.ex`; looks like mostly simple things (`Kernel.to_char_list/1 is deprecated`, `String.strip/2 is deprecated`, etc.). 

I know it's a bit weird but I really like having clean output (and especially having no warnings). Would you be open to a PR that fixes them?

**Comment by h4cc** [comment]
Thanks for the hint :)

Fixed with https://github.com/h4cc/slugger/commit/23b46a373843a00869bbaf0618a0530d49e1814e
