### ISSUE TITLE
Handle `'s ` specially?

### ISSUE THREAD

**Issue by nathanl** [h4cc/slugger#31]
I'm calling `String.replace(string, ~r/['’]s\s/u, "s ")` before passing the string to Slugger, because otherwise possessives look odd to me.

```
"Sheep's Milk"
|> Slugger.slugify_downcase() # => "sheep-s-milk" 🤔


"Sheep's Milk"
|> String.replace(~r/['’]s\s/u, "s ")
|> Slugger.slugify_downcase() # => "sheeps-milk" 😀
```

Is this something you think is worth changing in Slugger itself? (Maybe not, because it's multilingual?)

Feel free to 👎 and move on if you don't care to have this. If you want it, let me know and I'll PR.

**Comment by h4cc** [comment]
I like the idea. In the and the whole library is multilingual thingy :)
