### ISSUE TITLE
Unique slug?

### ISSUE THREAD

**Issue by lasseebert** [h4cc/slugger#7]
I'm using slugger to create a unique slug for some model.

I've implemented a function in my own app to handle this, where you give a function as parameter that can answer if the given slug is unique. If function returns falsy, it will try a new slug of the form `"#{slug}-#{counter}"`.

Is this in the scope of Slugger? If so I will be happy to make a PR.

e.g.:

``` elixir
article_name = "slugs are unique"
Slugger.slugify(name, fn(slug) -> Repo.unique_slug?(slug) end)
# => "slugs-are-unique-7"
```

One could imagine other (more performant) ways of finding the next slug for a given name, so this might not be general enough to include in a general slugging tool?

**Comment by h4cc** [comment]
Thanks for the idea.

But i can see multiple problems here:
Simply adding a counter is a strategy that is not very flexible.
The predicate if a slug is unique needs to be in a closure, like your example did.

I cant see a way to provide a function which can solve these problems ...

**Comment by lasseebert** [comment]
You're right. My simple wrapper function does the job for me just fine. Other projects might need other kinds of unique slugs.

**Comment by Morganjackson** [comment]
@lasseebert would you mind sharing an example of your solution? I think it would be very useful for others looking for a solution to this common problem.

**Comment by lasseebert** [comment]
Hi @Morganjackson 

I haven't used Slugger for a while (I abandoned the project where I used it), so this code might not be compatible with newest version of Slugger.

Here you go:

```elixir
defmodule MyApp.Slug do
  @moduledoc """
  Wrapper around Slugger to have all slugging isolated to one place

  Added functionality to create a unique slug given a uniqueness function
  """

  def build(input) do
    Slugger.slugify_downcase(input)
  end

  def build(input, unique_fun) do
    input
    |> build
    |> unique(input, unique_fun, 2)
  end

  defp unique(slug, input, unique_fun, next_counter) do
    if unique_fun.(slug) do
      slug
    else
      next_slug = build("#{input} #{next_counter}")
      next_slug
      |> unique(input, unique_fun, next_counter + 1)
    end
  end
end
```

**Comment by Morganjackson** [comment]
@lasseebert. Perfect! thank you.
