### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by valberg** [h4cc/slugger#9]
Awesome work! I was wondering if you have a plan of doing a new release to hex.pm? :smile:

**Comment by h4cc** [comment]
Yeah, that would be cool, but which stuff should be done till then?

How about #1 #2 #3 #11 ?

**Comment by joshprice** [comment]
A new release would be great, we're using this in a bunch of projects. Anything you need a hand with?

**Comment by h4cc** [comment]
Took about 565 days, but here it is :)

https://github.com/h4cc/slugger/releases/tag/v0.2.0

Thanks to all contributors!
